routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Support\Facades\DB;

Route::get('/', function () {
    return view('welcome');
});

/* Route::get('/', 'CartController@index')->name('cart.index'); */

/* Route::get('/test/{parametro?}', function ($parametro = null) {
    return 'mi numero es: '.$parametro;
}); */


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//example with querybuilder
route::get('/consulta-querybuilder', function(){
    //$fruits = DB::table('fruits')->orderBy('id', 'desc')->get();
    //$fruits = DB::table('fruits')->where('fruit', 'Aguacate')->first();
    //$fruits = DB::table('fruits')->count();
    $fruits = \DB::table('fruits')->max('price');
    echo "<pre>";
    var_dump($fruits);
    echo "</pre>";
});


//rutas de nuestro crud de test
Route::get('/test', 'TestController@index')->name('test.index');
Route::get('/create-test', 'TestController@create');
Route::post('/store-test', 'TestController@store')->name('test.store');







//crud de frutas con el ORM de laravel eloquent (query builder)
//php artisan route:list
Route::resource('/fruits', 'FruitController');

//rutas del modelo de productos
Route::get('/products-list', 'ProductController@index')->name('products.index');
Route::get('/products-create', 'ProductController@create')->name('products.create');
Route::get('/products-edit/{id}', 'ProductController@edit')->name('products.edit');
Route::post('/products-store', 'ProductController@store')->name('products.store');
Route::get('/products-path/{filename}', 'ProductController@getImgProduct')->name('products.path');
Route::put('/products-update/{id}', 'ProductController@update')->name('products.update');


//rutas del modelo de clientes
Route::resource('/clients', 'ClientController');

//rutas de herencia
Route::get('/herencia', function(){
    return view('test.herencia');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


//ejemplo herencia vistas de voyager
Route::get('/view-voyager', function(){
    $clientes = \DB::table('clients')->get();
    return view('voyager.test-view',[
        'clients' => $clientes
    ]);
});

//rutas de mi carrito de compras
Route::get('/carrito-index', 'CartController@index')->name('cart.index');
Route::get('/add-cart', 'CartController@addcart');

app/Fruit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Fruit extends Model
{
    protected $table = "fruits";

    protected $fillable = [
        'fruit', 'price', 'description',
    ];

}

app/Http/Controllers/FruitController.php
<?php

namespace App\Http\Controllers;

use App\Fruit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class FruitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //este metodo va a devolver todas las frutas que hay en la base de datos
        $fruits = Fruit::orderBy('id', 'desc')->paginate(5); 
        return view('fruits.index', [
            'fruits' => $fruits
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('fruits.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $fruit = new Fruit();
        $fruit->fruit = $request->input('fruit');
        $fruit->price = $request->input('price');
        $fruit->description = $request->input('description');

        if ($fruit->save()) {
            return redirect()->route('fruits.index')->with(['success' => 'Fruta '.$fruit->fruit.' creada exitosamente']);
        }
        //var_dump($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Fruit  $fruit
     * @return \Illuminate\Http\Response
     */
    public function show(Fruit $fruit)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Fruit  $fruit
     * @return \Illuminate\Http\Response
     */
    public function edit(Fruit $fruit)
    {
        return view('fruits.edit',[
            'fruit' => $fruit
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Fruit  $fruit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Fruit $fruit)
    {
        $fruit = Fruit::find($fruit->id);
        $fruit->fruit = $request->input('fruit');
        $fruit->price = $request->input('price');
        $fruit->description = $request->input('description');
        
        if ($fruit->update()) {
            return redirect()->route('fruits.index')->with(['success' => 'Fruta '.$fruit->fruit.' actualizada exitosamente']);
        }
        /* echo $fruit.'<br>';
        echo "<pre>";
        var_dump($request->all());
        echo "</pre>"; */
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Fruit  $fruit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Fruit $fruit)
    {
        $fruit = Fruit::find($fruit->id);
        if ($fruit->delete()) {
            return redirect()->route('fruits.index')->with(['success' => 'Fruta '.$fruit->fruit.' eliminada exitosamente']);
        }
    }
}

resources/views/fruits/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create new fruit</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('fruits.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="fruit" class="col-md-4 col-form-label text-md-right">{{ __('fruit') }}</label>

                            <div class="col-md-6">
                                <input id="fruit" type="text" class="form-control @error('fruit') is-invalid @enderror" name="fruit" value="{{ old('fruit') }}" required autocomplete="fruit" autofocus>

                                @error('fruit')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('price') }}</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price') }}" required autocomplete="price" autofocus>

                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" required autocomplete="description" autofocus></textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-sm btn-dark">
                                    {{ __('Create new fruit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/fruits/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Update fruit</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('fruits.update', ['fruit' => $fruit]) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="fruit" class="col-md-4 col-form-label text-md-right">{{ __('fruit') }}</label>

                            <div class="col-md-6">
                                <input id="fruit" type="text" class="form-control @error('fruit') is-invalid @enderror" name="fruit" value="{{ $fruit->fruit }}" required autocomplete="fruit" autofocus>

                                @error('fruit')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="price" class="col-md-4 col-form-label text-md-right">{{ __('price') }}</label>

                            <div class="col-md-6">
                                <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ $fruit->price }}" required autocomplete="price" autofocus>

                                @error('price')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('description') }}</label>

                            <div class="col-md-6">
                                <textarea id="description" class="form-control @error('description') is-invalid @enderror" name="description" required autocomplete="description" autofocus>{{ $fruit->description }}</textarea>

                                @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-sm btn-warning">
                                    {{ __('Update fruit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/fruits/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    {{ session('success') }}
                </div>
            @endif

            <div class="card mb-2">
                <div class="card-header">Lista de frutas</div>

                <div class="card-body">

                    @if (count($fruits))
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>Fruta</th>
                                    <th>Precio</th>
                                    <th>Descripción</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($fruits as $fruit)
                                    <tr>
                                        <td>{{ $fruit->id }}</td>
                                        <td>{{ $fruit->fruit }}</td>
                                        <td>{{ $fruit->price }}</td>
                                        <td>{{ $fruit->description }}</td>
                                        <td>
                                            <div class="btn-group" role="group" aria-label="Basic example">
                                                <a href="{{ route('fruits.edit', ['fruit' => $fruit]) }}" class="btn btn-warning">Editar</a>
                                                <form action="{{ route('fruits.destroy', ['fruit' => $fruit]) }}" method="POST">
                                                    @method('DELETE')
                                                    @csrf
                                                    <input type="submit" class="btn btn-danger" value="Eliminar">
                                                </form>
                                                {{-- <a href="{{ route('fruits.destroy', ['fruit' => $fruit]) }}" class="btn btn-danger">Eliminar</a> --}}
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>  
                        </table>
                    @else
                        <ul>
                            <li>No hay frutas registradas!!!</li>
                        </ul>
                    @endif
                    
                </div>
            </div>
            {{ $fruits->links() }}
        </div>
    </div>
</div>
@endsection