routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Illuminate\Support\Facades\DB;

Route::get('/', function () {
    return view('welcome');
});

/* Route::get('/', 'CartController@index')->name('cart.index'); */

/* Route::get('/test/{parametro?}', function ($parametro = null) {
    return 'mi numero es: '.$parametro;
}); */


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


//example with querybuilder
route::get('/consulta-querybuilder', function(){
    //$fruits = DB::table('fruits')->orderBy('id', 'desc')->get();
    //$fruits = DB::table('fruits')->where('fruit', 'Aguacate')->first();
    //$fruits = DB::table('fruits')->count();
    $fruits = \DB::table('fruits')->max('price');
    echo "<pre>";
    var_dump($fruits);
    echo "</pre>";
});


//rutas de nuestro crud de test
Route::get('/test', 'TestController@index')->name('test.index');
Route::get('/create-test', 'TestController@create');
Route::post('/store-test', 'TestController@store')->name('test.store');







//crud de frutas con el ORM de laravel eloquent (query builder)
//php artisan route:list
Route::resource('/fruits', 'FruitController');

//rutas del modelo de productos
Route::get('/products-list', 'ProductController@index')->name('products.index');
Route::get('/products-create', 'ProductController@create')->name('products.create');
Route::get('/products-edit/{id}', 'ProductController@edit')->name('products.edit');
Route::post('/products-store', 'ProductController@store')->name('products.store');
Route::get('/products-path/{filename}', 'ProductController@getImgProduct')->name('products.path');
Route::put('/products-update/{id}', 'ProductController@update')->name('products.update');


//rutas del modelo de clientes
Route::resource('/clients', 'ClientController');

//rutas de herencia
Route::get('/herencia', function(){
    return view('test.herencia');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


//ejemplo herencia vistas de voyager
Route::get('/view-voyager', function(){
    $clientes = \DB::table('clients')->get();
    return view('voyager.test-view',[
        'clients' => $clientes
    ]);
});

//rutas de mi carrito de compras
Route::get('/carrito-index', 'CartController@index')->name('cart.index');
Route::get('/add-cart', 'CartController@addcart');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table = "clients";

    protected $fillable = [
        'name', 'lastname', 'document', 'email', 'phone',
    ];
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::orderBy('id', 'desc')->paginate(5);
        return view('clients.index', [
            'clients' => $clients
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $this->validate($request, [
            'document' => 'required|max:255|unique:clients',
            'email' => 'required|string|email|max:255|unique:clients',
        ]);

        $client = new Client();
        $client->name = $request->input('name');
        $client->lastname = $request->input('lastname');
        $client->document = $request->input('document');
        $client->email = $request->input('email');
        $client->phone = $request->input('phone');

        $client->save();

        return redirect()->route('clients.index')->with(['success' => 'Cliente '.$client->name.' creado exitosamente']);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('clients.edit', [
            'client' => $client
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $client = Client::find($client->id);
        $client->name = $request->input('name');
        $client->lastname = $request->input('lastname');
        $client->document = $request->input('document');
        $client->email = $request->input('email');
        $client->phone = $request->input('phone');

        $client->update();
        return redirect()->route('clients.index')->with(['success' => 'Cliente '.$client->name.' actualizado exitosamente']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        //
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create new client</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('clients.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="lastname" class="col-md-4 col-form-label text-md-right">{{ __('lastname') }}</label>

                            <div class="col-md-6">
                                <input id="lastname" type="text" class="form-control @error('lastname') is-invalid @enderror" name="lastname" value="{{ old('lastname') }}" required autocomplete="lastname" autofocus>

                                @error('lastname')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="document" class="col-md-4 col-form-label text-md-right">{{ __('document') }}</label>

                            <div class="col-md-6">
                                <input id="document" class="form-control @error('document') is-invalid @enderror" name="document" value="{{ old('document') }}" required autocomplete="document" autofocus>

                                @error('document')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('email') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('phone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="phone" class="form-control @error('phone') is-invalid @enderror" name="phone" required autocomplete="phone" autofocus>

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-sm btn-dark">
                                    {{ __('Create new client') }}
                                </button>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Update client</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('clients.update', ['client' => $client]) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $client->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="lastname" class="col-md-4 col-form-label text-md-right">{{ __('lastname') }}</label>

                            <div class="col-md-6">
                                <input id="lastname" type="text" class="form-control @error('lastname') is-invalid @enderror" name="lastname" value="{{ $client->lastname }}" required autocomplete="lastname" autofocus>

                                @error('lastname')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="document" class="col-md-4 col-form-label text-md-right">{{ __('document') }}</label>

                            <div class="col-md-6">
                                <input id="document" class="form-control @error('document') is-invalid @enderror" name="document" value="{{ $client->document }}" required autocomplete="document" autofocus>

                                @error('document')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('email') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $client->email }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('phone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="phone" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ $client->phone }}" required autocomplete="phone" autofocus>

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-sm btn-dark">
                                    {{ __('Update to '.$client->name.'') }}
                                </button>
                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">

            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    {{ session('success') }}
                </div>
            @endif

            <div class="card mb-2">
                <div class="card-header">List clients</div>

                <div class="card-body table-responsive">

                    @if (count($clients))
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>id</th>
                                    <th>name</th>
                                    <th>lastname</th>
                                    <th>document</th>
                                    <th>email</th>
                                    <th>phone</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($clients as $client)
                                    <tr>
                                        <td>{{ $client->id }}</td>
                                        <td>{{ $client->name }}</td>
                                        <td>{{ $client->lastname }}</td>
                                        <td>{{ $client->document }}</td>
                                        <td>{{ $client->email }}</td>
                                        <td>{{ $client->phone }}</td>
                                        <td>
                                            <a href="{{ route('clients.edit', ['client' => $client]) }}" class="btn btn-sm btn-warning">Update</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>  
                        </table>
                    @else
                        <ul>
                            <li>No hay clientes registrados!!!</li>
                        </ul>
                    @endif
                    
                </div>
            </div>
             {{ $clients->links() }} 
        </div>
    </div>
</div>
@endsection